# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
fail_fast: false
default_language_version:
    python: python3
default_stages:
-   commit
-   push
minimum_pre_commit_version: 2.7.1
repos:
-   repo: https://github.com/deeenes/unexport
    rev: 0.4.0-patch0-8
    hooks:
    -   id: unexport
        args: [--refactor, --single_quotes]
        exclude: __init__.py$
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.0
    hooks:
    -   id: ruff
        args: [--fix]
    -   id: ruff-format
-   repo: https://github.com/myint/unify
    rev: v0.5
    hooks:
    -   id: unify
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: detect-private-key
    -   id: check-ast
    -   id: check-docstring-first
    -   id: end-of-file-fixer
    -   id: check-added-large-files
    -   id: mixed-line-ending
        args: [--fix=lf]
        exclude: ^docs/make.bat$
    -   id: trailing-whitespace
        exclude: ^.bumpversion.cfg$
    -   id: check-merge-conflict
    -   id: check-case-conflict
    -   id: check-symlinks
    -   id: check-yaml
        args: [--unsafe]
    -   id: fix-encoding-pragma
        args: [--remove]
    -   id: requirements-txt-fixer
-   repo: https://github.com/rstcheck/rstcheck
    rev: v6.1.2
    hooks:
    -   id: rstcheck
        exclude: docs
-   repo: https://github.com/asottile/blacken-docs
    rev: 1.13.0
    hooks:
    -   id: blacken-docs
-   repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
    rev: v2.8.0
    hooks:
    -   id: pretty-format-yaml
        args: [--autofix, --indent, '4']
-   repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.10.0
    hooks:
    -   id: python-use-type-annotations
    -   id: rst-backticks
    -   id: rst-directive-colons
    -   id: rst-inline-touching-normal
