version: 2

sphinx:
    configuration: docs/src/conf.py

build:
    os: ubuntu-22.04
    tools:
        python: "3.10"

python:
    install:
    -   method: pip
        path: .
    -   requirements: docs/src/requirements.txt