name: Test installation (& dependencies)

on:
  push:
    branches:
      - main
      - dev

jobs:
  test-install-import:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: ["3.10", "3.11", "3.12"]

    steps:

      - name: Checkout
        uses: actions/checkout@main

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
          cache-dependency-glob: uv.lock

      - name: Install package
        run: |
          uv sync --locked --no-dev

      - name: Import package
        run: |
          uv run --locked python -c "import networkcommons"
